#include <stdio.h>
#include <unistd.h>

//Question: how many processes will be generated by the following codes??
int main()
{
	fork();
	fork() && fork() || fork();
	fork();
	//printf("+/n");
    sleep(5000);
	return 0;
}
